version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 8080:80
      - 443:443
    # restart: always
    environment:
      # DOMAINS: 'web.local -> http://web:8008'
      DOMAINS: 'test.local -> http://web:8008'
      STAGE: local
    volumes:
      - ./org-chimata-ssl-certs:/var/lib/https-portal

  web:
    image: nginx:alpine
    ports:
      - 8008:8008
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - https-portal